-- Extended vendor/user/inquiry fields + Review table.
-- IDEMPOTENT + additive: adds only missing columns/table/FKs, never drops.
-- Safe to run on a fresh DB, an old-schema DB, or re-run.


SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='User' AND COLUMN_NAME='google_id');
SET @ddl := IF(@x=0, 'ALTER TABLE `User` ADD COLUMN `google_id` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='alternateMobile');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `alternateMobile` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='website');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `website` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='instagram');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `instagram` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='facebook');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `facebook` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='youtube');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `youtube` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='businessTimings');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `businessTimings` TEXT NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='yearsExperience');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `yearsExperience` INTEGER NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='teamSize');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `teamSize` INTEGER NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='serviceAreas');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `serviceAreas` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='languagesSpoken');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `languagesSpoken` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='acceptsDestination');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `acceptsDestination` BOOLEAN NOT NULL DEFAULT false', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Vendor' AND COLUMN_NAME='googleBusiness');
SET @ddl := IF(@x=0, 'ALTER TABLE `Vendor` ADD COLUMN `googleBusiness` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Inquiry' AND COLUMN_NAME='callDiscussion');
SET @ddl := IF(@x=0, 'ALTER TABLE `Inquiry` ADD COLUMN `callDiscussion` VARCHAR(191) NULL', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS `Review` (
    `id` VARCHAR(191) NOT NULL,
    `vendorId` VARCHAR(191) NOT NULL,
    `inquiryId` VARCHAR(191) NULL,
    `name` VARCHAR(191) NOT NULL,
    `rating` DOUBLE NOT NULL,
    `text` TEXT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `Review_inquiryId_key`(`inquiryId`),
    INDEX `Review_vendorId_createdAt_idx`(`vendorId`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='Review' AND CONSTRAINT_NAME='Review_vendorId_fkey');
SET @ddl := IF(@x=0, 'ALTER TABLE `Review` ADD CONSTRAINT `Review_vendorId_fkey` FOREIGN KEY (`vendorId`) REFERENCES `Vendor`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @x := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='Review' AND CONSTRAINT_NAME='Review_inquiryId_fkey');
SET @ddl := IF(@x=0, 'ALTER TABLE `Review` ADD CONSTRAINT `Review_inquiryId_fkey` FOREIGN KEY (`inquiryId`) REFERENCES `Inquiry`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'DO 0');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
