#!/usr/bin/env node
/**
 * Builds the Hostinger-ready deployment zip from the current working tree.
 *
 *   node build-deploy.js
 *
 * Produces ./wedeazzy-production-ready.zip with the app files at the zip root
 * (so extracting it into the Node app root drops app.js straight in place).
 *
 * Excluded: node_modules (installed on the server), tests, the local dev .env,
 * the device-bound WhatsApp session, and the PII directories (kyc-private,
 * import-staging). backend/.env is REGENERATED as a production config from the
 * local one — see buildProdEnv() — with a fresh JWT_SECRET and FILL_ME for the
 * two values that can only come from hPanel.
 */
const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const ROOT = __dirname;
const DOMAIN = process.env.DEPLOY_DOMAIN || 'https://wedeazzy.com';
const ZIP = path.join(ROOT, 'wedeazzy-production-ready.zip');
const STAGE = path.join(os.tmpdir(), 'wedeazzy-production-deploy');

const ROOT_FILES = ['app.js', 'package.json', 'DEPLOY-HOSTINGER.md', 'README.md', '.htaccess'];
const BACKEND_FILES = [
  'package.json', 'package-lock.json', '.env.example', 'ecosystem.config.js',
  'DEPLOY.md', 'README.md', 'Dockerfile', 'docker-compose.yml',
];
const BACKEND_DIRS = ['src', 'prisma'];
const WRITABLE_DIRS = ['uploads', 'logs', 'baileys-auth', 'kyc-private', 'import-staging'];
// Local-only debugging scripts that have no business on a production box.
const SKIP_FILES = new Set(['inspect_claimed_demo.js']);

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || SKIP_FILES.has(entry.name)) continue;
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(from, to);
    else fs.copyFileSync(from, to);
  }
}

/** Reads one KEY=value out of the local backend/.env. */
function localEnv(key) {
  const src = fs.readFileSync(path.join(ROOT, 'backend', '.env'), 'utf8');
  const m = src.match(new RegExp('^' + key + '=(.*)$', 'm'));
  return m ? m[1].trim() : '';
}

function buildProdEnv() {
  const g = localEnv;
  const jwt = crypto.randomBytes(64).toString('hex');
  return `# WedEazzy backend — PRODUCTION environment.
# Generated by build-deploy.js. Replace every FILL_ME before first boot.
# Contains live credentials — never commit it, never place it inside public_html.

# --- Server ---
NODE_ENV=production
PORT=4000
PUBLIC_BASE_URL=${DOMAIN}
# Comma-separated. Must match exactly what the browser sends. No trailing slash.
FRONTEND_ORIGIN=${DOMAIN},${DOMAIN.replace('https://', 'https://www.')}

# --- Database (MySQL) ---
# From hPanel > Databases > Management. URL-encode special chars in the password:
#   @ -> %40   # -> %23   / -> %2F   : -> %3A
DATABASE_URL="mysql://FILL_ME_USER:FILL_ME_PASSWORD@localhost:3306/FILL_ME_DBNAME"

# --- JWT ---
# Freshly generated for this build. Changing it later logs out every user.
JWT_SECRET=${jwt}
JWT_EXPIRES_IN=${g('JWT_EXPIRES_IN') || '30d'}

# --- OTP ---
OTP_TTL_MIN=${g('OTP_TTL_MIN') || '5'}
OTP_MAX_PER_HOUR=${g('OTP_MAX_PER_HOUR') || '5'}
OTP_LENGTH=${g('OTP_LENGTH') || '6'}
# MUST stay false in production (true leaks one-time codes in logs and responses).
OTP_DEBUG_LOG=false
# Returns the one-time code in the API response when SMTP delivery FAILS, so a
# vendor is not locked out by a broken mail server. Deliberately off: SMTP is
# configured and verified, and anything that puts a login code in an HTTP
# response is a login bypass for whoever asks for it. Turn on only to debug a
# confirmed mail outage, and turn it back off afterwards.
OTP_FALLBACK_ENABLED=false

# --- Baileys / WhatsApp ---
# Shared/Cloud hosting sleeps the process, so WhatsApp will not stay paired there.
BAILEYS_AUTH_DIR=${g('BAILEYS_AUTH_DIR') || './baileys-auth'}
WA_MAX_RECONNECT_ATTEMPTS=${g('WA_MAX_RECONNECT_ATTEMPTS') || '10'}
WA_RECONNECT_BASE_MS=${g('WA_RECONNECT_BASE_MS') || '3000'}
WA_RETRY_MAX_ATTEMPTS=${g('WA_RETRY_MAX_ATTEMPTS') || '3'}
WA_RETRY_BACKOFF_MS=${g('WA_RETRY_BACKOFF_MS') || '300000'}

# --- Admin ---
ADMIN_PHONES=${g('ADMIN_PHONES')}
ADMIN_EMAIL=${g('ADMIN_EMAIL')}
# Bootstrap password for the first admin login. Pick a strong one, then CHANGE IT
# in the admin panel right after you log in — it sits here in plaintext.
ADMIN_PASSWORD=FILL_ME
SUPPORT_EMAIL=${g('SUPPORT_EMAIL')}

# --- Legacy vendor import (one-off migration script only) ---
LEGACY_DB_PASSWORD=

# --- Uploads ---
UPLOAD_DIR=${g('UPLOAD_DIR') || './uploads'}
MAX_UPLOAD_MB=${g('MAX_UPLOAD_MB') || '5'}

# --- Razorpay ---
RAZORPAY_KEY_ID=${g('RAZORPAY_KEY_ID')}
RAZORPAY_KEY_SECRET=${g('RAZORPAY_KEY_SECRET')}
RAZORPAY_WEBHOOK_SECRET=${g('RAZORPAY_WEBHOOK_SECRET')}

# --- NVIDIA NIM (public FAQ chatbot free-text fallback) — optional ---
NVIDIA_NIM_API_KEY=${g('NVIDIA_NIM_API_KEY')}

# --- SMTP ---
SMTP_HOST=${g('SMTP_HOST')}
SMTP_PORT=${g('SMTP_PORT') || '465'}
SMTP_USER=${g('SMTP_USER')}
SMTP_PASS=${g('SMTP_PASS')}
SMTP_FROM=${g('SMTP_FROM')}
SMTP_SECURE=${g('SMTP_SECURE') || 'true'}

# --- Google OAuth ---
# Register this exact callback URL in Google Cloud Console > Credentials.
GOOGLE_CLIENT_ID=${g('GOOGLE_CLIENT_ID')}
GOOGLE_CLIENT_SECRET=${g('GOOGLE_CLIENT_SECRET')}
GOOGLE_CALLBACK_URL=${DOMAIN}/google/callback

# --- Google Sheet CSV Source ---
GOOGLE_SHEET_CSV_URL=${g('GOOGLE_SHEET_CSV_URL')}
`;
}

fs.rmSync(STAGE, { recursive: true, force: true });
fs.mkdirSync(STAGE, { recursive: true });

for (const f of ROOT_FILES) {
  const from = path.join(ROOT, f);
  if (fs.existsSync(from)) fs.copyFileSync(from, path.join(STAGE, f));
}
copyDir(path.join(ROOT, 'public'), path.join(STAGE, 'public'));

const backendOut = path.join(STAGE, 'backend');
fs.mkdirSync(backendOut, { recursive: true });
for (const f of BACKEND_FILES) {
  const from = path.join(ROOT, 'backend', f);
  if (fs.existsSync(from)) fs.copyFileSync(from, path.join(backendOut, f));
}
for (const d of BACKEND_DIRS) copyDir(path.join(ROOT, 'backend', d), path.join(backendOut, d));
for (const d of WRITABLE_DIRS) {
  fs.mkdirSync(path.join(backendOut, d), { recursive: true });
  fs.writeFileSync(path.join(backendOut, d, '.gitkeep'), '');
}
fs.writeFileSync(path.join(backendOut, '.env'), buildProdEnv());

fs.rmSync(ZIP, { force: true });
execFileSync('powershell.exe', [
  '-NoProfile', '-Command',
  `Add-Type -AssemblyName System.IO.Compression.FileSystem; ` +
  `[System.IO.Compression.ZipFile]::CreateFromDirectory('${STAGE}','${ZIP}',` +
  `[System.IO.Compression.CompressionLevel]::Optimal,$false)`,
], { stdio: 'inherit' });

const mb = (fs.statSync(ZIP).size / 1024 / 1024).toFixed(2);
console.log(`\nBuilt ${path.basename(ZIP)} (${mb} MB)`);
console.log('Fill in DATABASE_URL and ADMIN_PASSWORD in backend/.env after extracting.');
